### ISSUE TITLE
Pull from Omnifocus doesn't change item name in Omniplan

### ISSUE THREAD

**Issue by aw237** [richm8080/OmniPlanFocusSync#2]
Hi,

thanks for these scripts!

I noticed one issue: Pull from Omnifocus does transfer completions, but it doesn't synchronize changes in the item name back to Omniplan.

Best regards

**Comment by richm8080** [comment]
Hello!

Thanks for reaching out and for highlighting this issue.
I've updated the scripts to update the task names when pulling from OmniFocus, see if this does what you want, let me know if anything isn't working and i'll take another look.

Kind regards,
Rich

**Comment by aw237** [comment]
Great, I can confirm that the scripts are now working flawlessly. 
I was looking for a a way to synchronize tasks between OmniFocus and OmniPlan including the completion. Really appreciate your work on this!
Best,
Adrian
